### ISSUE TITLE
Update Station - Broken

### ISSUE THREAD

**Issue by Lindsor** [getstation/desktop-app#245]
- Application version: 2.3
 - OS: MacOS 14.1 M2

**Steps to Reproduce:**

1. Download station 2.3
2. Go to `Settings`
3. Click on `Check for updates`
4. Click on `Quit to update Station`
5. See Station quits correctly but it never re-opens and never updates.

**Comment by NithyaMenon** [comment]
I'm experiencing the same thing! I cannot figure out how to get it to update..

Application version: 2.3
OS: MacOS 13.4.1 M1

**Comment by libroraptor** [comment]
"Quit to update" still wasn't working in 2.7.0 for MacOS

**Comment by libroraptor** [comment]
Works in Mac v 2.7.1 but I found this out by accident: I was intending to shut it down, and it re-started to run v 2.7.2.

I suggest that it not restart automatically when we close the app because we actually want to close the app.

**Comment by karimbenbourenane** [comment]
Does this have anything to do with the fact that [releases/downloads/v3.3.0/latest-mac.yml](https://github.com/getstation/desktop-app/releases/download/v3.3.0/latest-mac.yml ) has an old version number?


```
version: 3.1.0-b3
files:
  - url: Station.zip
    sha512: 1xF4D/GSuTBp/8EG0G5EMtc+2tEM0ZB5x6VvNqex9EAbyvDP7LC0qAezJUA6bbEiSY7DrRCAgl8Oh3m4DKP5CQ==
    size: 229177061
path: Station.zip
sha512: 1xF4D/GSuTBp/8EG0G5EMtc+2tEM0ZB5x6VvNqex9EAbyvDP7LC0qAezJUA6bbEiSY7DrRCAgl8Oh3m4DKP5CQ==
releaseDate: '2024-07-12T07:56:05.837Z'
```
